### ISSUE TITLE
Receiving files fails under macOS

### ISSUE THREAD

**Issue by khinsen** [aurelg/ipfs-wormhole#11]
Unfortunately, the options for `/usr/bin/base64` are not the same under macOS as under Linux. Decoding requires `-D` instead of `-d`. I just edited line 134 by hand, but a more bash-savvy person could probably make the script portable.

**Comment by aurelg** [comment]
Thanks your report. Should work with commit f376d50. You can test it and if it works as expected, close this ticket :-)

**Comment by khinsen** [comment]
Works fine, thanks!
